-- Paramétrage applicatif à portée organisationnelle (global / direction / service).
-- Décision et schéma détaillés dans docs/ARCHITECTURE.md ("Paramétrage applicatif") ;
-- policies RLS détaillées dans ForClaude/SECURITY.md §2.3.
-- Suppose l'existence préalable de finances.direction, finances.service,
-- finances.acteur, finances.role_attribution et des fonctions
-- public.current_user_matricule() / finances.current_user_has_role() (créées hors
-- migration versionnée sur l'instance Supabase existante).

create table finances.parametre_application (
  id_parametre  integer primary key generated by default as identity,
  cle           text not null,               -- ex: 'fad.objet.max_length'
  valeur        jsonb not null,               -- nombre, booléen, texte ou objet — typé nativement
  id_direction  integer references finances.direction (id_direction),
  id_service    integer references finances.service (id_service),
  description   text,
  date_maj      timestamptz not null default now(),
  matricule_maj text references finances.acteur (matricule),
  -- portée mutuellement exclusive, même patron que le CHECK de role_attribution
  -- (ForClaude/CDC/mld-phases-1-2.md §105)
  constraint parametre_application_portee_exclusive check (
    (id_direction is null and id_service is null)        -- global
    or (id_direction is not null and id_service is null) -- par direction
    or (id_direction is null and id_service is not null) -- par service (direction résolue par jointure sur finances.service, jamais dupliquée ici)
  )
);

comment on table finances.parametre_application is
  'Paramètres applicatifs modifiables sans déploiement, portée global/direction/service '
  'résolue en cascade (le plus spécifique gagne). Géré exclusivement par ADMIN_APP.';

-- Une seule valeur par clé à chaque niveau de portée. NULL n'étant jamais égal à NULL,
-- un UNIQUE classique sur (cle, id_direction, id_service) n'empêcherait pas les doublons
-- global/direction — trois index partiels, un par niveau (même patron que les unicités
-- RC/CDS/DS de role_attribution, ForClaude/CDC/mld-phases-1-2.md §95-96).
create unique index parametre_application_global_uk
  on finances.parametre_application (cle)
  where id_direction is null and id_service is null;

create unique index parametre_application_direction_uk
  on finances.parametre_application (cle, id_direction)
  where id_direction is not null;

create unique index parametre_application_service_uk
  on finances.parametre_application (cle, id_service)
  where id_service is not null;

-- GRANT ≠ POLICY (ForClaude/SECURITY.md §2.2) : préalable indispensable avant les policies.
grant usage on schema finances to authenticated;
grant select, insert, update, delete on finances.parametre_application to authenticated;

alter table finances.parametre_application enable row level security;

-- Lecture : ouverte à tout authenticated rattaché à un ACTEUR (matricule non null) — un
-- acteur doit pouvoir lire les paramètres effectifs de son propre périmètre et les
-- valeurs globales, quel que soit son rôle métier (RC, CDS, DS, CB, ADMIN_SERVICE...).
create policy "parametre_application_select_authenticated"
  on finances.parametre_application
  for select
  to authenticated
  using (public.current_user_matricule() is not null);

-- Écriture : réservée à ADMIN_APP, quelle que soit la portée de la ligne visée — jamais de
-- policy permettant à un DS/ADMIN_SERVICE d'écrire sur le périmètre de sa propre
-- direction/service (contrairement à seuil_validation_ds : décision produit propre à
-- parametre_application, voir ForClaude/SECURITY.md §2.3).
create policy "parametre_application_insert_admin_app"
  on finances.parametre_application
  for insert
  to authenticated
  with check (finances.current_user_has_role('ADMIN_APP'));

create policy "parametre_application_update_admin_app"
  on finances.parametre_application
  for update
  to authenticated
  using (finances.current_user_has_role('ADMIN_APP'))
  with check (finances.current_user_has_role('ADMIN_APP'));

create policy "parametre_application_delete_admin_app"
  on finances.parametre_application
  for delete
  to authenticated
  using (finances.current_user_has_role('ADMIN_APP'));
